### ISSUE TITLE
关于echarts的需求

### ISSUE THREAD

**Issue by hiyangguo** [hypers/pagurian#18]
- [x] 希望提供[echarts折柱图](http://echarts.baidu.com/doc/example/mix1.html)的二次封装实现
- [x] 希望提供[echarts环形图](http://echarts.baidu.com/doc/example/pie2.html)的二次封装实现
- [x] 希望提供[echarts堆积柱状图](http://echarts.baidu.com/doc/example/bar2.html)的二次封装实现

**Comment by simonguo** [comment]
http://pagurian.com/dist/templates/echarts-mashup-linebar.html
http://pagurian.com/dist/templates/echarts-pie-loop.html
http://pagurian.com/dist/templates/echarts-bar-stack.html
