### ISSUE TITLE
1.6 版本开发计划

### ISSUE THREAD

**Issue by simonguo** [hypers/pagurian#20]
- [x] 增加图表的图例
- [x] 添加Tree 组件
- [x] 修复上个版本中存在的bug
- [x] 添加Number Spinner 插件

**Comment by hiyangguo** [comment]
![zTree插件](https://git.oschina.net/zTree/zTree_v3) 我觉得不多各种api非常全面
我看了他在开源中国的issue作者认真的对待了每一个需求和问题 并且逐一详细解答，我觉得真心不错

**Comment by hiyangguo** [comment]
![jsTree](https://github.com/vakata/jstree) 这个是一个和上面差不多的插件 api也蛮丰富的

**Comment by JexCheng** [comment]
alert可以考虑不同的message type分成不同的方法，就像`console.error`、`console.info` 一样，我觉得这样更好一些:
https://github.com/hypers/pagurian/blob/dev/src/lib/com/alert.js#L3

```
alert(msg,"info"); // 换成 alert.info(msg) 之类的
alert(msg,"sucess"); // 这样type拼写错了并没有检查机制，换成 alert.success(msg) 可以触发显式报错，节省debug时间
```

可以保留原来的接口，只增加：
```
const MSG_TYPES = ["success","info","error","warning",""];
MSG_TYPES.forEach((t) => {
  alert[t]= (msg) => alert(msg,t);
});
```

当然可能名称要变一下，`alert`即是警告的意思，感觉`$p.warn(msg)`比`alert.warning(msg)`更顺口一点

**Comment by JexCheng** [comment]
可以省略一些不必要的或不恰当的`new Class`：

https://github.com/hypers/pagurian/blob/dev/src/lib/tool/str.js

https://github.com/hypers/pagurian/blob/dev/src/lib/tool/tool.js

https://github.com/hypers/pagurian/blob/dev/src/lib/tool/url.js

作为模块对象不需要有多个实例的，直接这样更好：
```javascript
var tool = {
   log: function () {/*....*/},
   getQueryString: function () {/*....*/}
};
```

尤其是 `new URL` 那个会造成误解（ [window.URL](https://developer.mozilla.org/en-US/docs/Web/API/Window/URL) ）。

另外在未来是否应该考虑应用模块加载器提供的 exports 机制？
```javascript
define(function(require, exports, module) {
    exports.log = function () {/*....*/};
});
```

利用  [CoC 原则/约定胜于配置](https://en.wikipedia.org/wiki/Convention_over_configuration) ，约定一个模块命名空间为 `/lib/tool/str`，就自动注册到`$PagurianAlias.tool.str`上，当然这个点要推迟讨论，现在的不好改。

**Comment by JexCheng** [comment]
https://github.com/hypers/pagurian/blob/dev/src/widgets/sizer/module.js
widgets/sizer 的 options 中 callbackXXX 之类的选项考虑是否适合定义成事件

**Comment by JexCheng** [comment]
另外 core/tpl 不知功能是否足够，sea.js好像支持import html模板文件，可以考虑将像Sizer这样的widgets中的大段HTML放到外部文件，然后用 tpl 填充数据得到 _sizerSelectPanel。

PS：这些小问题放在开发计划下面好像不太适合，是否需要另开一个issue讨论？
