### ISSUE TITLE
ehcarts渲染问题

### ISSUE THREAD

**Issue by hiyangguo** [hypers/pagurian#32]
1.echatrs update的时候如果数据多次为空则会多次创建

``` html
<div class="chart-message">
    <h3><i class="icon icon-info icon-big"></i> 查询结果为空</h3>
</div>
```

2.查询数据为空时调用showLoading方法不能显示loading动画

**Comment by simonguo** [comment]
已修复
https://github.com/hypers/pagurian/commit/f8306b84e735231951bffa0a443a07d3edb0c79b
