### ISSUE TITLE
建议使用handlebars4.0.0的partials语法为菜单添加高亮

### ISSUE THREAD

**Issue by hiyangguo** [hypers/pagurian#37]
发现hanbars可以使用`tag="value"`为`{{tag}}`赋值,详见[handlebars4.0.0的partials语法](http://handlebarsjs.com/partials.html),想到可以在base.hbs中添加

``` javascript
window.CONFIG = {
        appId: "{{hoverMenu}}"
};
```

再在每个页面中

``` html
{{#>base hoverMenu="menuName"}}
{{/base}}
```

即可实现更加优雅的菜单高亮页面
此方案优于之前的在`app.js`顶部配置`window.CONGIG`

**Comment by simonguo** [comment]
已添加
