### ISSUE TITLE
Datatable里面的三角点击没效果？

### ISSUE THREAD

**Issue by slaggs** [hypers/pagurian#52]
Datatable里面的三角点击没效果，是只是装饰还是怎么

**Comment by simonguo** [comment]
你是说的排序功能吗？  demo 中的数据是静态的.json 文件 ，所有点击以后没有排序展示。  点击后可以在api请求中看到一个请求参数orderColumn， 服务端的api会根据这个参数的值字段进行排序，返回排序后的数据

**Comment by slaggs** [comment]
这个是框架可以自动处理的还是要投胎处理

**Comment by simonguo** [comment]
orderColumn 参数是默认加的，也可以修改参数名，参考：http://pagurian.com/demo/dist/templates/datatable-options.html
自定义参数名 sOrderColumn。  没有投胎处理😓

**Comment by slaggs** [comment]
手误手误是后台处理
